name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: '1.0.0'
        required: true
        type: string
      skip_notarization:
        description: 'Set to true to skip macOS notarization during the build.'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Create .env file
        run: |
          echo "VITE_OPENAI_API_KEY=${{ secrets.VITE_OPENAI_API_KEY }}" >> .env
          echo "VITE_ANTHROPIC_API_KEY=${{ secrets.VITE_ANTHROPIC_API_KEY }}" >> .env
          echo "VITE_GOOGLE_API_KEY=${{ secrets.VITE_GOOGLE_API_KEY }}" >> .env
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
          echo "VITE_TAVILY_API_KEY=${{ secrets.VITE_TAVILY_API_KEY }}" >> .env
          echo "VITE_GH_TOKEN=${{ secrets.VITE_GH_TOKEN }}" >> .env

      # Build with notarization (default)
      - name: Build application (macOS)
        if: matrix.os == 'macos-latest' && (github.event_name != 'workflow_dispatch' || github.event.inputs.skip_notarization != 'true')
        run: bun run build:release
        env:
          NODE_ENV: production
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

      # Build without notarization when the flag is set
      - name: Build application (macOS – skip notarization)
        if: matrix.os == 'macos-latest' && github.event_name == 'workflow_dispatch' && github.event.inputs.skip_notarization == 'true'
        run: bun run build:release -- -c.mac.notarize=false
        env:
          NODE_ENV: production
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # explicitly disable identity auto-discovery so electron-builder doesn't try to find a signing cert
          CSC_IDENTITY_AUTO_DISCOVERY: "false"

      - name: Build application (Windows/Linux)
        if: matrix.os != 'macos-latest'
        run: bun run build:release
        env:
          NODE_ENV: production
          # fully disable any signing autodiscovery so electron-builder skips Win code-sign
          CSC_IDENTITY_AUTO_DISCOVERY: "false"

      - name: Upload artifacts (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            release/*.dmg
            release/*.zip
            release/*.yml
            release/*.blockmap

      - name: Upload artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            release/*.exe
            release/*.yml
            release/*.blockmap

      - name: Upload artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            release/*.AppImage
            release/*.yml
            release/*.blockmap

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release in public repository
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          PUBLIC_REPO: ${{ secrets.PUBLIC_REPO_NAME }}
        run: |
          # Get version from tag or input
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          
          # Create release notes
          echo "## Wagoo $VERSION" > release_notes.md
          echo "" >> release_notes.md
          echo "Download the appropriate version for your platform:" >> release_notes.md
          echo "" >> release_notes.md
          echo "- **macOS**: Download the .dmg file" >> release_notes.md
          echo "- **Windows**: Download the .exe file" >> release_notes.md
          echo "- **Linux**: Download the .AppImage file" >> release_notes.md
          echo "" >> release_notes.md
          echo "### Changes" >> release_notes.md
          git log --oneline --since="$(git describe --tags --abbrev=0 HEAD^)..HEAD" >> release_notes.md || echo "First release" >> release_notes.md
          
          # Create release in public repo
          gh release create "$VERSION" \
            --repo "$PUBLIC_REPO" \
            --title "Wagoo $VERSION" \
            --notes-file release_notes.md \
            macos-build/* \
            windows-build/* \
            linux-build/* \
            macos-build/*/*.yml \
            macos-build/*/*.blockmap \
            windows-build/*/*.yml \
            windows-build/*/*.blockmap \
            linux-build/*/*.yml \
            linux-build/*/*.blockmap 